# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: CDL_Validation
# label used for menu selection
label: Validate Cortex Data Lake configurations
description: Long form description of the purpose and function of this Skillet.

# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: pan_validation
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - IoT
    - CDL

# ---------------------------------------------------------------------
# end of preamble section

# variables section
# ---------------------------------------------------------------------
# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints examples include text, ip_address, or dropdown

# ---------------------------------------------------------------------
# end of variables section

# snippets section
# ---------------------------------------------------------------------
snippets:
# example output capture and test structure layout
  - name: device_config_file
    cmd: parse
    variable: config
    outputs:
      - name: cdl_enabled
        capture_value: /config/devices/entry/deviceconfig/setting/logging/logging-service-forwarding/enable/text()

  - name: cdl_enabled_test
    label: cdl enabled globally
    test:  cdl_enabled == "yes"

    fail_message: |
      CDL must be enabled in the device to push logs to the cloud
    pass_message: CDL is globally enabled
    documentation_link: https://docs.paloaltonetworks.com/cortex/cortex-data-lake/cortex-data-lake-getting-started/get-started-with-cortex-data-lake/key.html

  - name: device_config_file
    cmd: parse
    variable: config
    outputs:
      - name: logging_service_regions
        capture_value: /config/devices/entry/deviceconfig/setting/logging/logging-service-forwarding/logging-service-regions/text()

  - name: logging_service_regions_test
    label: logging service region set
    test:  logging_service_regions | length

    fail_message: |
      No region chosen, Need to on-board firewall and license to CDL in order to choose region
    pass_message: Firewall region is set as {{logging_service_regions}}
    documentation_link: https://docs.paloaltonetworks.com/cortex/cortex-data-lake/cortex-data-lake-getting-started/get-started-with-cortex-data-lake/key.html

  - name: device_config_file
    cmd: parse
    variable: config
    outputs:
      - name: enhanced_application_logging_enabled
        capture_value: /config/devices/entry/deviceconfig/setting/logging/enhanced-application-logging/enable/text()

  - name: enhanced_application_logging_enabled_test
    label: eal enabled globally
    test:  enhanced_application_logging_enabled == "yes"

    fail_message: |
      EAL must be enabled in the device to push logs to CDL services
    pass_message: EAL is globally enabled
    documentation_link: https://docs.paloaltonetworks.com/cortex/cortex-data-lake/cortex-data-lake-getting-started/get-started-with-cortex-data-lake/key.html

  - name: get_logging_status
    cmd: cli
        # This cli command will return a text blob
    cmd_str: show logging-status
    output_type: text
    outputs:
          # let's capture a variable called 'connected_server_ip'
      - name: capture_traffic_counters
            # this will search the text returned from the cli command and return the first match found using this regex
            # pattern
        capture_pattern: config\s{2,}(.*?)\s{2,}(.*?)\s{2,}

# this will capture ALL matches from the following regex as a list. No matches always return an empty list
      - name: all_cms
        capture_list: Not Sending to CMS (\d+)

  - name: capture_last_log_created
    label: Checking if traffic logs are created
    test: |
      (
      capture_traffic_counters[0] != "Not Available"
      and capture_traffic_counters[0] | length != 0
      )
    fail_message: |
      Traffic logs are not being created
    pass_message: "{{capture_traffic_counters[0]}}"
    documentation_link: https://knowledgebase.paloaltonetworks.com/KCSArticleDetail?id=kA10g000000CmMtCAK

  - name: capture_last_log_forwarded
    label: Checking if traffic logs are forwarded
    test: capture_traffic_counters[1] != "Not Available" and capture_traffic_counters[1] | length

    fail_message: |
      Traffic logs are not being forwarded
    pass_message: "{{capture_traffic_counters[1]}}"
    documentation_link: https://knowledgebase.paloaltonetworks.com/KCSArticleDetail?id=kA10g000000CmMtCAK


  - name: verification
    cmd: cli
        # This cli command will return a text blob
    cmd_str: request logging-service-forwarding certificate info
    output_type: text
    outputs:
          # capture a variable called 'cert_chain_verification'
      - name: cert_chain_verification
        capture_pattern: Certificate chain verification:\s{1,2}(.*?)\s{1,2}
      - name: private_public_key_match
        capture_pattern: Public and private key pair match:\s{1,2}(.*?)\s{1,2}
      - name: certificate_expired
        capture_pattern: Certificate expired:\s{1,2}(.*?)\s{1,2}

  - name: cert_chain_verification_test
    label: test to see if the cert verification is there or not
    test: cert_chain_verification == "OK"
    fail_message: |
      Certificate chain is not verified
    pass_message: Certificate chain is verified
    documentation_link: https://docs.paloaltonetworks.com/cortex/cortex-data-lake/cortex-data-lake-getting-started/get-started-with-cortex-data-lake/key.html

  - name: private_public_key_match_test
    label: Test key match
    test: private_public_key_match == "Yes"
    fail_message: |
      There is no private public key match
    pass_message: There is a private public key match
    documentation_link: https://docs.paloaltonetworks.com/cortex/cortex-data-lake/cortex-data-lake-getting-started/get-started-with-cortex-data-lake/key.html

  - name: certificate_expired_test
    label: Test certificate expiration
    test: certificate_expired == "No"
    fail_message: |
      Certificate has expired
    pass_message: Certificate is valid
    documentation_link: https://docs.paloaltonetworks.com/cortex/cortex-data-lake/cortex-data-lake-getting-started/get-started-with-cortex-data-lake/key.html

  - name: cortexDataLake
    cmd: cli
    cmd_str: request logging-service-forwarding customerinfo show
    outputs:
      - name: fullResponse
        capture_object: /custinfo
      - name: CDLregion
        capture_value: /custinfo/entry[@name="1"]/region-name/text()
      - name: CDLcustomerID
        capture_value: /custinfo/entry[@name="1"]/customer-id/text()

  - name: CDLregion_test
    label: test if CDL region set
    test:  CDLregion | length

    fail_message: |
      No CDL region present, check if certificate fetch is successful
    pass_message: Firewall region is set as {{CDLregion}}
    documentation_link: https://knowledgebase.paloaltonetworks.com/KCSArticleDetail?id=kA10g000000CmMtCAK

  - name: CDLcustomerID_test
    label: test if CDL customerID set
    test:  CDLcustomerID | length

    fail_message: |
      No CDL Customer ID present, check if certificate fetch is successful
    pass_message: Firewall region is set as {{CDLcustomerID}}
    documentation_link: https://knowledgebase.paloaltonetworks.com/KCSArticleDetail?id=kA10g000000CmMtCAK

  - name: device_config_file
    cmd: parse
    variable: config
    outputs:

    # get list of profiles from both (Test and Default)
    #that are sending to panorama via xpath
      - name: sending_to_panorama_enabled
        capture_list: |-
          /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/log-settings/profiles/entry
          /match-list/entry/send-to-panorama[text()='yes']/../@name

    # Xpath gets list of all possible profiles then filter to profiles that
    # are not in sending_to_panorama AKA they arent sending to panorama
    # filter_items then goes through the top list and determines if it's present in this
    # profiles_not_sending_panorama list, if it's not present it filters it out.
      - name: profiles_not_sending_panorama
        capture_list: |-
          /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/log-settings/profiles/entry/match-list/entry/send-to-panorama/../@name
        filter_items: item not in sending_to_panorama_enabled

      # get the complete object to parse for output message values
      - name: log_settings_object
        capture_object: |-
          /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/log-settings/profiles/entry


  - name: check_sending_to_panorama_enabled
    label: check that all profiles are sending to Cortex Data Lake
  #if this test passes that means there is nothing in profiles_not_sending_panorama
  #meaning that every profile is currently sending to panorama
    test: profiles_not_sending_panorama | length == 0
    severity: high
    fail_message: |
      profiles not sending to panorama are:
      (profile name, rule name, log type)
      {%- for profile_entry in log_settings_object %}
        {%- for key, profile in profile_entry.items() %}
          {%- set profile_name = profile['@name'] %}
          {%- for key2, matchList in profile['match-list'].items() %}
            {%- for logRule in matchList %}
              {%- if logRule['send-to-panorama'] == 'no' %}
                {{ profile_name }}, {{ logRule['@name'] }}, {{ logRule['log-type'] }}
              {%- endif %}
            {%- endfor %}
          {%- endfor %}
        {%- endfor %}
      {%- endfor %}
    pass_message: |
      all profiles are sending to panorama
    documentation_link: https://docs.paloaltonetworks.com/pan-os/9-0/pan-os-admin/monitoring/configure-log-forwarding.html

  - name: device_config_file
    cmd: parse
    variable: config
    outputs:

    # get list of the profiles that have EAL enabled via xpath below
      - name: eal_enabled
        capture_list: |-
          /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/log-settings/profiles/entry
          /enhanced-application-logging[text()='yes']/../@name

    # Xpath gets list of all possible profiles then filter to profiles that
    # are not in eal_enabled which means they don't have EAL enabled
    # filter_items then goes through the top list and determines if it's present in this
    # eal_not_enabled list, if it's not present it filters it out.
      - name: eal_not_enabled
        capture_list: |-
          /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/log-settings/profiles/entry/@name
        filter_items: item not in eal_enabled


  - name: check_eal_enabled
    label: check that all profiles have eal enabled
  #if this test passes that means there is nothing in eal_not_enabled
  #meaning that every profile currently has eal enabled
    test: eal_not_enabled | length == 0
    severity: high
    fail_message: |
      profiles that don't have eal enabled are: {{ eal_not_enabled }}
    pass_message: |
      all profiles have eal enabled
    documentation_link: https://docs.paloaltonetworks.com/pan-os/8-1/pan-os-admin/monitoring/enhanced-application-logs

# ---------------------------------------------------------------------
# end of snippets section
